### ISSUE TITLE
Determining which Header a Scale belongs to

### ISSUE THREAD

**Issue by ScottGuthart** [mhermher/savvy#5]
Hey there,

Is there a way to determine which `Header` entry a `Scale` belongs to?

It looks like each `Scale` (in `internals.levels`) has a `Set` of `indices` that indicate which columns they belong to but I gather these indices correspond to internal columns and not the ones that appear in the list of `Headers` since the range of indices in my own dataset is much larger than the number of `Header` entries.

For example, how would I figure out that the `Header` for gender below corresponds to the `Scale` entry shown in `parsed.internal.levels`?

```javascript
...
const parsed = {
  // ... other Parsed entries
  headers: [
   {
      name: 'Gender',
      label:  'What gender do you identify with?',
   }
   // ... other Headers 
  ],
  internal: {
  levels: [
    indices: {5},
    map: {1 => 'Male', 2 => 'Female', 3 => 'Other'},
  ],
  // ... other Internal entries
  }
```

Edit: It looks like I can do something like this to get the Scale entry for a column if I pass the `label` from the Header entry:
```javascript
const dataset = new Savvy(parsed)
const column = dataset.field('Gender')
console.log(column)
/**
  _levels: {1 => 'Male', 2 => 'Female', 3 => 'Other'},
  // ... rest of column entries
*/
```

**Comment by mhermher** [comment]
Yes. The `Header` and `Scale` that come out of parsing the file are offset and don't match up intuitively. You can use the `Savvy` class (as you discovered in your edit) to do the matching logic for you. You can see the source code for the Savvy constructor to see how it is done, but basically, we record a `trailers` property for each of the headers that indicates how much to offset the indices by. Each header takes (1 + header.trailers) spaces in the offset index.

**Comment by mhermher** [comment]
Resolved by using Savvy class
